[tool.black]
line-length=100

[tool.isort]
default_section="THIRDPARTY"
known_first_party=["plyflatten"]
multi_line_output=3
include_trailing_comma=true
force_grid_wrap=0
use_parentheses=true
line_length=100
